"""
SQLAlchemy async database layer for the Samni Labs backend.

Exposes:
  * `Base`                — declarative base used by all ORM models (db_models.py).
  * `init_db()`           — called once at FastAPI / worker startup; builds the
                            async engine and session factory, verifies connectivity.
  * `shutdown_db()`       — disposes the pool at shutdown.
  * `get_db_session()`    — async context manager for node functions and
                            background tasks. Auto-rollback on exception,
                            auto-close on exit. Commits are EXPLICIT — the
                            caller (a node) owns the transaction boundary.
  * `get_db()`            — FastAPI dependency yielding an AsyncSession.
  * `check_db_connectivity()` — non-raising probe used by /health.

Security posture for a PHI database:
  * TLS is required on every connection in non-dev (`ssl=require` via asyncpg).
  * `statement_timeout=30s` server-side — a runaway / malicious query cannot
    pin a connection indefinitely.
  * `idle_in_transaction_session_timeout=60s` — a held transaction cannot
    block VACUUM or DDL forever.
  * `lock_timeout=10s` — callers fail fast instead of waiting on blocked rows.
  * `pool_pre_ping=True` — dead RDS connections after failover are detected
    and recycled before returning to the caller.
  * `pool_recycle=1800` — connections older than 30 min are closed; defeats
    stale-connection issues behind NLB/proxies.
  * `DB_ECHO` is forced OFF in non-dev — echo logs bound parameters, which
    would stream PHI values into stdout. Enforced at init time.
  * Session objects NEVER hold a transaction across a `yield` to untrusted
    code — `get_db_session` guarantees close-on-exit.
  * Every parameter that reaches SQL goes through SQLAlchemy binding; this
    module does not expose any `execute(text(...))` path that takes raw
    user input.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator, Optional

from sqlalchemy import MetaData, event, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from config import Settings, get_settings


logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Declarative base
# --------------------------------------------------------------------------- #
# A consistent naming convention is critical for Alembic: without it,
# autogenerated migrations produce randomly-named indexes/constraints that
# diverge between environments and make downgrades hazardous.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ORM model in db_models.py."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# --------------------------------------------------------------------------- #
# Module-level singletons (set by init_db, cleared by shutdown_db)
# --------------------------------------------------------------------------- #
_engine: Optional[AsyncEngine] = None
_SessionLocal: Optional[async_sessionmaker[AsyncSession]] = None


# --------------------------------------------------------------------------- #
# Engine / session construction
# --------------------------------------------------------------------------- #
def _build_connect_args(settings: Settings) -> dict:
    """
    Construct the asyncpg `connect_args` dict with hardened defaults.

    `server_settings` values are SET on the PostgreSQL session at connect
    time — they cannot be disabled by a later query from a compromised
    component.
    """
    server_settings: dict[str, str] = {
        # Identifies this service in pg_stat_activity — ops can find slow
        # queries by app without grepping logs.
        "application_name": f"samni-backend-{settings.ENVIRONMENT}",
        # Hard cap on any single query. 30s is far above normal traffic for
        # the queries this app issues (point lookups + small JSONB upserts).
        "statement_timeout": "30000",
        # Kill transactions that sit idle holding locks. Protects VACUUM and
        # prevents a hung worker from blocking the whole pipeline.
        "idle_in_transaction_session_timeout": "60000",
        # Fail fast instead of queuing behind a row lock.
        "lock_timeout": "10000",
    }

    connect_args: dict = {"server_settings": server_settings}

    # TLS required for any non-dev deployment. In dev we tolerate a plaintext
    # localhost connection; in staging/production the engine refuses to open
    # a plaintext channel to RDS.
    if not settings.is_dev:
        connect_args["ssl"] = "require"

    return connect_args


def _build_engine(settings: Settings) -> AsyncEngine:
    """Create a new async engine honoring all pool + timeout settings."""

    # DB_ECHO in non-dev would echo bound parameters (PHI) to stdout. Refuse.
    echo = bool(settings.DB_ECHO)
    if echo and not settings.is_dev:
        raise RuntimeError(
            "DB_ECHO=True is forbidden outside the dev environment because "
            "echoed SQL bound parameters would leak PHI into logs."
        )

    engine = create_async_engine(
        settings.DATABASE_URL,
        echo=echo,
        pool_size=settings.DB_POOL_SIZE,
        max_overflow=settings.DB_MAX_OVERFLOW,
        pool_timeout=settings.DB_POOL_TIMEOUT,
        pool_pre_ping=True,
        pool_recycle=1800,
        connect_args=_build_connect_args(settings),
        # future=True is the SQLAlchemy 2.x default but explicit is better.
        future=True,
    )

    _attach_connection_listeners(engine)
    return engine


def _attach_connection_listeners(engine: AsyncEngine) -> None:
    """
    Attach lightweight listeners to the underlying sync engine.

    We keep these at DEBUG and do not log any query text — only connection
    lifecycle metadata so pool issues are debuggable without emitting PHI.
    """

    @event.listens_for(engine.sync_engine, "connect")
    def _on_connect(dbapi_connection, connection_record) -> None:  # type: ignore[no-untyped-def]
        connection_record.info["pid"] = id(dbapi_connection)
        logger.debug("DB connection opened cid=%s", connection_record.info["pid"])

    @event.listens_for(engine.sync_engine, "checkout")
    def _on_checkout(dbapi_connection, connection_record, connection_proxy) -> None:  # type: ignore[no-untyped-def]
        logger.debug(
            "DB connection checked out cid=%s",
            connection_record.info.get("pid"),
        )

    @event.listens_for(engine.sync_engine, "close")
    def _on_close(dbapi_connection, connection_record) -> None:  # type: ignore[no-untyped-def]
        logger.debug(
            "DB connection closed cid=%s",
            connection_record.info.get("pid"),
        )


# --------------------------------------------------------------------------- #
# Public lifecycle
# --------------------------------------------------------------------------- #
async def init_db() -> None:
    """
    Initialize the engine and session factory, and verify connectivity.

    Called once from the FastAPI startup hook and once from the worker's
    entry point. Idempotent: a second call is a no-op.
    """
    global _engine, _SessionLocal

    if _engine is not None:
        logger.debug("init_db() called but engine already initialized; skipping")
        return

    settings = get_settings()
    engine = _build_engine(settings)

    # Verify connectivity before we commit to using this engine. This turns
    # a mis-configured DATABASE_URL into a startup failure rather than a
    # per-request 500.
    try:
        async with engine.connect() as conn:
            result = await conn.execute(text("SELECT 1"))
            value = result.scalar()
            if value != 1:
                raise RuntimeError(
                    f"Database SELECT 1 returned unexpected value: {value!r}"
                )
    except Exception:
        # Dispose the half-built engine so we don't leak sockets on crash.
        await engine.dispose()
        logger.exception("init_db: database connectivity check failed")
        raise

    _engine = engine
    _SessionLocal = async_sessionmaker(
        bind=_engine,
        class_=AsyncSession,
        expire_on_commit=False,
        autoflush=False,
        autocommit=False,
    )

    # Do NOT log the DSN — it may contain a password even though ops
    # typically use IAM auth. Log only the host component if present.
    try:
        from urllib.parse import urlparse

        host = urlparse(settings.DATABASE_URL).hostname or "unknown"
    except Exception:  # noqa: BLE001
        host = "unknown"

    logger.info(
        "Database initialized host=%s pool_size=%d max_overflow=%d ssl=%s",
        host,
        settings.DB_POOL_SIZE,
        settings.DB_MAX_OVERFLOW,
        "required" if not settings.is_dev else "optional",
    )


async def shutdown_db() -> None:
    """Dispose the engine and clear module state. Idempotent."""
    global _engine, _SessionLocal

    if _engine is None:
        return

    try:
        await _engine.dispose()
    except Exception:  # noqa: BLE001
        # Swallow at shutdown — we're already tearing down.
        logger.exception("shutdown_db: error disposing engine")

    _engine = None
    _SessionLocal = None
    logger.info("Database engine disposed")


# --------------------------------------------------------------------------- #
# Accessors (fail loudly if init_db was skipped)
# --------------------------------------------------------------------------- #
def get_engine() -> AsyncEngine:
    """Return the initialized engine or raise. Used by Alembic runtime hooks."""
    if _engine is None:
        raise RuntimeError(
            "Database engine has not been initialized. Call init_db() first."
        )
    return _engine


def get_sessionmaker() -> async_sessionmaker[AsyncSession]:
    """Return the initialized session factory or raise."""
    if _SessionLocal is None:
        raise RuntimeError(
            "Session factory has not been initialized. Call init_db() first."
        )
    return _SessionLocal


# --------------------------------------------------------------------------- #
# Session context manager + FastAPI dependency
# --------------------------------------------------------------------------- #
@asynccontextmanager
async def get_db_session() -> AsyncIterator[AsyncSession]:
    """
    Async context manager yielding a fresh `AsyncSession`.

    Contract:
      * Commits are the CALLER's responsibility (nodes do their own
        `await session.commit()`). This keeps transaction boundaries
        explicit — critical for the audit trail where commit order
        matters.
      * Any unhandled exception inside the `async with` block triggers a
        `rollback()` so partial writes never land.
      * The session is always closed on exit, even if commit/rollback
        themselves raise.
    """
    factory = get_sessionmaker()
    session: AsyncSession = factory()
    try:
        yield session
    except Exception:
        # Roll back defensively; if rollback itself fails we still want to
        # surface the ORIGINAL exception, so we log-and-swallow the rollback
        # error.
        try:
            await session.rollback()
        except Exception:  # noqa: BLE001
            logger.exception("get_db_session: rollback failed during exception unwind")
        raise
    finally:
        try:
            await session.close()
        except Exception:  # noqa: BLE001
            logger.exception("get_db_session: session.close() failed")


async def get_db() -> AsyncIterator[AsyncSession]:
    """
    FastAPI dependency.

    Usage:
        @app.get(...)
        async def handler(db: AsyncSession = Depends(get_db)): ...
    """
    async with get_db_session() as session:
        yield session


# --------------------------------------------------------------------------- #
# Health probe (never raises)
# --------------------------------------------------------------------------- #
async def check_db_connectivity() -> bool:
    """
    Lightweight probe used by /health. Returns True iff `SELECT 1` succeeds.
    Never raises — callers treat False as degraded.
    """
    if _engine is None:
        return False
    try:
        async with _engine.connect() as conn:
            result = await conn.execute(text("SELECT 1"))
            return result.scalar() == 1
    except Exception:  # noqa: BLE001
        logger.warning("check_db_connectivity: probe failed", exc_info=False)
        return False


__all__ = [
    "Base",
    "init_db",
    "shutdown_db",
    "get_engine",
    "get_sessionmaker",
    "get_db_session",
    "get_db",
    "check_db_connectivity",
]
