"""inital schema

Revision ID: 262038975ff9
Revises: 
Create Date: 2026-04-22 11:22:21.010481+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '262038975ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=True),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.CheckConstraint('length(patient_id) > 0', name=op.f('ck_patients_ck_patients_patient_id_nonempty')),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_facility_id'), 'patients', ['facility_id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('source_phrase', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('approval_method', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_method IN ('auto', 'human')", name=op.f('ck_audit_trail_ck_audit_trail_approval_method')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name=op.f('ck_audit_trail_ck_audit_trail_confidence_range')),
    sa.CheckConstraint('length(field_path) > 0', name=op.f('ck_audit_trail_ck_audit_trail_field_path_nonempty')),
    sa.CheckConstraint('length(patient_id) > 0', name=op.f('ck_audit_trail_ck_audit_trail_patient_id_nonempty')),
    sa.CheckConstraint('length(run_id) > 0', name=op.f('ck_audit_trail_ck_audit_trail_run_id_nonempty')),
    sa.CheckConstraint('length(user_id) > 0', name=op.f('ck_audit_trail_ck_audit_trail_user_id_nonempty')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='fk_audit_trail_patient_id_patients', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_trail'))
    )
    op.create_index(op.f('ix_audit_trail_created_at'), 'audit_trail', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_field_path'), 'audit_trail', ['field_path'], unique=False)
    op.create_index('ix_audit_trail_field_path_created_at', 'audit_trail', ['field_path', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_patient_id'), 'audit_trail', ['patient_id'], unique=False)
    op.create_index('ix_audit_trail_patient_id_created_at', 'audit_trail', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_trail_run_id'), 'audit_trail', ['run_id'], unique=False)
    op.create_index('ix_audit_trail_run_id_created_at', 'audit_trail', ['run_id', 'created_at'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('output_pdf_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('flagged_updates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pipeline_type IN ('intake', 'reassessment')", name=op.f('ck_pipeline_runs_ck_pipeline_runs_pipeline_type')),
    sa.CheckConstraint("status IN ('queued', 'running', 'waiting_review', 'complete', 'failed')", name=op.f('ck_pipeline_runs_ck_pipeline_runs_status')),
    sa.CheckConstraint('length(patient_id) > 0', name=op.f('ck_pipeline_runs_ck_pipeline_runs_patient_id_nonempty')),
    sa.CheckConstraint('length(run_id) > 0', name=op.f('ck_pipeline_runs_ck_pipeline_runs_run_id_nonempty')),
    sa.CheckConstraint('length(user_id) > 0', name=op.f('ck_pipeline_runs_ck_pipeline_runs_user_id_nonempty')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='fk_pipeline_runs_patient_id_patients', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_patient_id'), 'pipeline_runs', ['patient_id'], unique=False)
    op.create_index('ix_pipeline_runs_patient_id_created_at', 'pipeline_runs', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_pipeline_runs_patient_id_status', 'pipeline_runs', ['patient_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_runs_patient_id_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_patient_id_created_at', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_patient_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_audit_trail_run_id_created_at', table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_run_id'), table_name='audit_trail')
    op.drop_index('ix_audit_trail_patient_id_created_at', table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_patient_id'), table_name='audit_trail')
    op.drop_index('ix_audit_trail_field_path_created_at', table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_field_path'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_created_at'), table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_patients_facility_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
